### ISSUE TITLE
Code: 500 on generating password via vault-secrets-gen

### ISSUE THREAD

**Issue by typlo-gh** [sethvargo/vault-secrets-gen#31] opened 2021-10-20 06:53 UTC
I am getting code 500 on generating passwords via the latest vault (go-plugin).

root@uat-tekesvault001:/etc/vault.d/plugins# vault write gen/password length=36 symbols=0
Error writing data to gen/password: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/gen/password
Code: 500. Errors:

* 1 error occurred:
	* internal error

Note: The vault server is using a self-signed certificate.

Logs:

Oct 20 12:17:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:17:30.431+0530 [ERROR] secrets.secrets-gen.secrets-gen_29db1cb9.secrets-gen.vault-secrets-gen: plugin tls init: error="no vault api_addr fo>
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:17:30.432+0530 [ERROR] rollback: error rolling back: path=gen/
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:   error=
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:   | Unrecognized remote plugin message:
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:   |
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:   | This usually means that the plugin is either invalid or simply
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:   | needs to be recompiled to support the latest protocol.
Oct 20 12:17:30 uat-tekesvault001 vault[3421430]:
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:18:30.362+0530 [INFO]  expiration: revoked lease: lease_id=sys/wrapping/wrap/h2027eb13bfdb55aeeda926e639259645e563d1c3b5404439bbc118ec68213>
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:18:30.434+0530 [ERROR] secrets.secrets-gen.secrets-gen_29db1cb9.secrets-gen.vault-secrets-gen: plugin tls init: error="no vault api_addr fo>
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:18:30.435+0530 [ERROR] rollback: error rolling back: path=gen/
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:   error=
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:   | Unrecognized remote plugin message:
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:   |
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:   | This usually means that the plugin is either invalid or simply
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:   | needs to be recompiled to support the latest protocol.
Oct 20 12:18:30 uat-tekesvault001 vault[3421430]:
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]: 2021-10-20T12:18:57.568+0530 [ERROR] secrets.secrets-gen.secrets-gen_29db1cb9.secrets-gen.vault-secrets-gen: plugin tls init: error="no vault api_addr fo>
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]: 2021-10-20T12:18:57.569+0530 [ERROR] core: failed to run existence check:
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:   error=
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:   | Unrecognized remote plugin message:
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:   |
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:   | This usually means that the plugin is either invalid or simply
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:   | needs to be recompiled to support the latest protocol.
Oct 20 12:18:57 uat-tekesvault001 vault[3421430]:
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:19:30.367+0530 [INFO]  expiration: revoked lease: lease_id=sys/wrapping/wrap/hfad1ca76ee4e3f52bd13651c89e7f509a2c43fe4f0b082a83623d1e2ac44d>
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:19:30.429+0530 [ERROR] secrets.secrets-gen.secrets-gen_29db1cb9.secrets-gen.vault-secrets-gen: plugin tls init: error="no vault api_addr fo>
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:19:30.430+0530 [ERROR] rollback: error rolling back: path=gen/
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:   error=
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:   | Unrecognized remote plugin message:
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:   |
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:   | This usually means that the plugin is either invalid or simply
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:   | needs to be recompiled to support the latest protocol.
Oct 20 12:19:30 uat-tekesvault001 vault[3421430]:
Oct 20 12:19:57 uat-tekesvault001 vault[3421430]: 2021-10-20T12:19:57.502+0530 [INFO]  expiration: revoked lease: lease_id=sys/wrapping/wrap/hcb309e1c8cd4e6e398796b6abe866762de4a786ac94d16ee3de98c712022d>
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:20:30.361+0530 [INFO]  expiration: revoked lease: lease_id=sys/wrapping/wrap/hd65448c87790003e4d51ac0ec5165f856d05361d8cc4c383b55468be10211>
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:20:30.426+0530 [ERROR] secrets.secrets-gen.secrets-gen_29db1cb9.secrets-gen.vault-secrets-gen: plugin tls init: error="no vault api_addr fo>
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]: 2021-10-20T12:20:30.427+0530 [ERROR] rollback: error rolling back: path=gen/
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:   error=
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:   | Unrecognized remote plugin message:
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:   |
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:   | This usually means that the plugin is either invalid or simply
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:   | needs to be recompiled to support the latest protocol.
Oct 20 12:20:30 uat-tekesvault001 vault[3421430]:

**Comment by sethvargo** [comment] 2021-10-20 17:57
Looks like a duplicate of https://github.com/sethvargo/vault-secrets-gen/issues/30. Can you try the steps there?

**Closed as completed** 2021-10-22 05:51 UTC
